---
apiVersion: v1
kind: Namespace
metadata:
   name: udayjns
---
apiVersion: v1
kind: Pod
metadata:
  name: javawebapppod
  labels:
    app: javawebapp #very imp
  namespace: udayjns
spec:
  containers:
  - name: javaweappcontainer
    image: udayj8/maven-web-app
    ports:
      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebappsvc
  namespace: udayjns
spec:
  type: LoadBalancer
  selector:
    app: javawebapp  #POD label
  ports:
    - port: 80
      targetPort: 8080
...